import { describe, it, expect } from 'vitest';
import {
  detectResilienceTier,
  classifyPresenceStatus,
  isAutoGeneratedSelector,
  scoreSelectorResilience,
  rankSelectorsByResilience,
} from './selectorScorer';
import type {
  SelectorValidationResult,
  PrecedingStepContext,
} from '../types/skills';

describe('selectorScorer', () => {
  describe('detectResilienceTier', () => {
    it('detects TestId tier for data-testid and test attributes', () => {
      expect(detectResilienceTier('[data-testid="login-btn"]')).toBe('TestId');
      expect(detectResilienceTier('[data-test=submit]')).toBe('TestId');
      expect(detectResilienceTier('[data-cy="user-menu"]')).toBe('TestId');
      expect(detectResilienceTier('button[data-qa="confirm"]')).toBe('TestId');
    });

    it('detects AriaRole tier for role and aria attributes', () => {
      expect(detectResilienceTier('[role="button"][name="Submit"]')).toBe('AriaRole');
      expect(detectResilienceTier('role=navigation')).toBe('AriaRole');
      expect(detectResilienceTier('[aria-label="Close dialog"]')).toBe('AriaRole');
      expect(detectResilienceTier('getByRole("dialog")')).toBe('AriaRole');
    });

    it('detects VisibleText tier for text selectors', () => {
      expect(detectResilienceTier('text=Sign In')).toBe('VisibleText');
      expect(detectResilienceTier('button:has-text("Save")')).toBe('VisibleText');
      expect(detectResilienceTier('a:text("Dashboard")')).toBe('VisibleText');
    });

    it('detects StandardCss tier for simple classes and ids', () => {
      expect(detectResilienceTier('#main-header')).toBe('StandardCss');
      expect(detectResilienceTier('.btn-primary')).toBe('StandardCss');
      expect(detectResilienceTier('form input[type="email"]')).toBe('StandardCss');
    });

    it('detects DeepXPath tier for deep or complex xpath/css paths', () => {
      expect(detectResilienceTier('//div/div[2]/table/tbody/tr[3]/td[1]/button')).toBe('DeepXPath');
      expect(detectResilienceTier('/html/body/div[1]/main/section/div/p')).toBe('DeepXPath');
      expect(detectResilienceTier('div > div > div:nth-child(4) > span > a')).toBe('DeepXPath');
    });
  });

  describe('isAutoGeneratedSelector', () => {
    it('detects css-hash and dynamic id patterns', () => {
      expect(isAutoGeneratedSelector('.css-19vjh7')).toBe(true);
      expect(isAutoGeneratedSelector('#btn-928374')).toBe(true);
      expect(isAutoGeneratedSelector('.sc-bdVaJa')).toBe(true);
      expect(isAutoGeneratedSelector('div._3k8f9a')).toBe(true);
      expect(isAutoGeneratedSelector('#ember124')).toBe(true);
      expect(isAutoGeneratedSelector('#app-login-button')).toBe(false);
      expect(isAutoGeneratedSelector('.primary-btn')).toBe(false);
    });
  });

  describe('classifyPresenceStatus', () => {
    it('classifies 1 visible match as UniquePresent', () => {
      const probe: SelectorValidationResult = {
        valid: true,
        selector: '[data-testid="submit"]',
        selectorType: 'css',
        matchCount: 1,
        visibleCount: 1,
        matches: [{ tagName: 'button', isVisible: true, isClickable: true, isInShadowRoot: false }],
        durationMs: 4,
      };
      expect(classifyPresenceStatus(probe)).toBe('UniquePresent');
    });

    it('classifies >1 matches as AmbiguousMultiple', () => {
      const probe: SelectorValidationResult = {
        valid: true,
        selector: '.btn',
        selectorType: 'css',
        matchCount: 3,
        visibleCount: 2,
        matches: [],
        durationMs: 5,
      };
      expect(classifyPresenceStatus(probe)).toBe('AmbiguousMultiple');
    });

    it('classifies 0 matches without dynamic context as NotPresent', () => {
      const probe: SelectorValidationResult = {
        valid: true,
        selector: '#non-existent',
        selectorType: 'css',
        matchCount: 0,
        visibleCount: 0,
        matches: [],
        durationMs: 3,
      };
      expect(classifyPresenceStatus(probe)).toBe('NotPresent');
    });

    it('classifies 0 matches with preceding trigger steps as DeferredDynamic', () => {
      const probe: SelectorValidationResult = {
        valid: true,
        selector: '.modal-confirm',
        selectorType: 'css',
        matchCount: 0,
        visibleCount: 0,
        matches: [],
        durationMs: 3,
      };
      const preceding: PrecedingStepContext[] = [
        { action: 'leftClick', selector: '#open-dialog-btn' },
      ];
      expect(classifyPresenceStatus(probe, preceding)).toBe('DeferredDynamic');
    });
  });

  describe('scoreSelectorResilience', () => {
    it('scores high-resilience unique testId selector as reliable (score >= 90)', () => {
      const probe: SelectorValidationResult = {
        valid: true,
        selector: '[data-testid="confirm-order"]',
        selectorType: 'css',
        matchCount: 1,
        visibleCount: 1,
        matches: [{
          tagName: 'button',
          testId: 'confirm-order',
          isVisible: true,
          isClickable: true,
          isInShadowRoot: false,
        }],
        durationMs: 2,
      };

      const report = scoreSelectorResilience('[data-testid="confirm-order"]', probe);
      expect(report.tier).toBe('TestId');
      expect(report.status).toBe('UniquePresent');
      expect(report.score).toBeGreaterThanOrEqual(95);
      expect(report.isReliable).toBe(true);
      expect(report.warnings).toHaveLength(0);
    });

    it('penalizes ambiguous multiple matches and autogenerated classes', () => {
      const probe: SelectorValidationResult = {
        valid: true,
        selector: '.css-19vjh7',
        selectorType: 'css',
        matchCount: 4,
        visibleCount: 3,
        matches: [],
        durationMs: 5,
      };

      const report = scoreSelectorResilience('.css-19vjh7', probe);
      expect(report.status).toBe('AmbiguousMultiple');
      expect(report.score).toBeLessThan(40);
      expect(report.isReliable).toBe(false);
      expect(report.warnings).toContain('Matches multiple elements on page');
      expect(report.warnings).toContain('Appears to use autogenerated/hashed identifiers');
    });

    it('generates suggestions when element contains testId or role attributes', () => {
      const probe: SelectorValidationResult = {
        valid: true,
        selector: '//div/button',
        selectorType: 'xpath',
        matchCount: 1,
        visibleCount: 1,
        matches: [{
          tagName: 'button',
          testId: 'save-btn',
          role: 'button',
          textPreview: 'Save Changes',
          isVisible: true,
          isClickable: true,
          isInShadowRoot: false,
        }],
        durationMs: 3,
      };

      const report = scoreSelectorResilience('//div/button', probe);
      expect(report.suggestions).toBeDefined();
      expect(report.suggestions?.some(s => s.includes('[data-testid="save-btn"]'))).toBe(true);
    });
  });

  describe('rankSelectorsByResilience', () => {
    it('ranks candidates in descending order of resilience score', () => {
      const candidates = [
        '//div[1]/button[2]',
        '[data-testid="checkout-btn"]',
        'text=Checkout',
        '.css-98f2',
      ];

      const probeMap = new Map<string, SelectorValidationResult>([
        [
          '[data-testid="checkout-btn"]',
          {
            valid: true,
            selector: '[data-testid="checkout-btn"]',
            selectorType: 'css',
            matchCount: 1,
            visibleCount: 1,
            matches: [{ tagName: 'button', isVisible: true, isClickable: true, isInShadowRoot: false }],
            durationMs: 2,
          },
        ],
        [
          'text=Checkout',
          {
            valid: true,
            selector: 'text=Checkout',
            selectorType: 'text',
            matchCount: 1,
            visibleCount: 1,
            matches: [{ tagName: 'button', isVisible: true, isClickable: true, isInShadowRoot: false }],
            durationMs: 2,
          },
        ],
      ]);

      const ranked = rankSelectorsByResilience(candidates, probeMap);
      expect(ranked[0].selector).toBe('[data-testid="checkout-btn"]');
      expect(ranked[1].selector).toBe('text=Checkout');
      expect(ranked[0].score).toBeGreaterThan(ranked[1].score);
    });
  });
});
