import type {
  SelectorValidationResult,
  SelectorScoreReport,
  SelectorResilienceTier,
  SelectorPresenceStatus,
  PrecedingStepContext,
} from '../types/skills';

// Base scores mapped to stability hierarchy
const TIER_SCORES: Record<SelectorResilienceTier, number> = {
  TestId: 100,
  AriaRole: 85,
  VisibleText: 70,
  StandardCss: 50,
  DeepXPath: 20,
};

// Common regexes for auto-generated identifiers and framework hashes
const AUTO_HASH_PATTERNS = [
  /\.css-[a-z0-9]+/i,
  /\.sc-[a-zA-Z0-9]+/i,
  /\._[a-z0-9]{5,}/i,
  /#[a-z0-9_-]*\d{5,}[a-z0-9_-]*/i,
  /#ember\d+/i,
  /\[class\*=["']?css-[a-z0-9]+/i,
];

/**
 * Detect the stability tier of a given selector string.
 */
export function detectResilienceTier(selector: string): SelectorResilienceTier {
  const trimmed = selector.trim();

  // TestID / QA / Cypress attributes
  if (
    /\[data-(?:testid|test|qa|cy)=/i.test(trimmed) ||
    /data-(?:testid|test|qa|cy)=/i.test(trimmed)
  ) {
    return 'TestId';
  }

  // Aria and semantic role queries
  if (
    /\[role=/i.test(trimmed) ||
    /role=/i.test(trimmed) ||
    /\[aria-(?:label|labelledby|description)=/i.test(trimmed) ||
    /getByRole\(/i.test(trimmed)
  ) {
    return 'AriaRole';
  }

  // Visible text selectors
  if (
    trimmed.startsWith('text=') ||
    /:has-text\(/i.test(trimmed) ||
    /:text\(/i.test(trimmed)
  ) {
    return 'VisibleText';
  }

  // Deep XPath or brittle structural CSS
  if (
    trimmed.startsWith('//') ||
    trimmed.startsWith('/html') ||
    trimmed.split('>').length > 3 ||
    (trimmed.match(/:nth-child\(/g)?.length ?? 0) >= 2
  ) {
    return 'DeepXPath';
  }

  return 'StandardCss';
}

/**
 * Check if the selector contains autogenerated/hashed classes or ids.
 */
export function isAutoGeneratedSelector(selector: string): boolean {
  return AUTO_HASH_PATTERNS.some((pattern) => pattern.test(selector));
}

/**
 * Determine if a preceding step could trigger a dynamic DOM change (modals, dropdowns, menus).
 */
export function isDynamicTriggerStep(step: PrecedingStepContext): boolean {
  const action = step.action.toLowerCase();
  const sel = (step.selector || '').toLowerCase();

  if (action === 'leftclick' || action === 'tap' || action === 'hover') {
    return (
      sel.includes('modal') ||
      sel.includes('dialog') ||
      sel.includes('menu') ||
      sel.includes('dropdown') ||
      sel.includes('open') ||
      sel.includes('btn') ||
      sel.includes('button') ||
      sel.includes('toggle') ||
      sel.includes('expand')
    );
  }
  return false;
}

/**
 * Classify selector presence status from probe results and optional flow context.
 */
export function classifyPresenceStatus(
  probeResult?: SelectorValidationResult,
  precedingSteps?: PrecedingStepContext[]
): SelectorPresenceStatus {
  if (!probeResult || !probeResult.valid) {
    // Check if there's preceding dynamic context
    if (precedingSteps && precedingSteps.some(isDynamicTriggerStep)) {
      return 'DeferredDynamic';
    }
    return 'NotPresent';
  }

  if (probeResult.matchCount === 1) {
    return 'UniquePresent';
  }

  if (probeResult.matchCount > 1) {
    return 'AmbiguousMultiple';
  }

  // matchCount === 0
  if (precedingSteps && precedingSteps.some(isDynamicTriggerStep)) {
    return 'DeferredDynamic';
  }

  return 'NotPresent';
}

/**
 * Generate actionable suggestions from matched element metadata.
 */
function generateSuggestions(
  probeResult: SelectorValidationResult,
  currentTier: SelectorResilienceTier
): string[] {
  const suggestions: string[] = [];
  const primaryMatch = probeResult.matches[0];

  if (!primaryMatch) return suggestions;

  if (primaryMatch.testId && currentTier !== 'TestId') {
    suggestions.push(`[data-testid="${primaryMatch.testId}"]`);
  }

  if (primaryMatch.role && currentTier !== 'AriaRole') {
    if (primaryMatch.textPreview) {
      suggestions.push(`[role="${primaryMatch.role}"][name="${primaryMatch.textPreview.slice(0, 30)}"]`);
    } else {
      suggestions.push(`[role="${primaryMatch.role}"]`);
    }
  }

  if (primaryMatch.textPreview && currentTier !== 'VisibleText' && currentTier !== 'TestId') {
    const cleanText = primaryMatch.textPreview.trim().slice(0, 40);
    if (cleanText.length > 2) {
      suggestions.push(`text=${cleanText}`);
    }
  }

  return suggestions;
}

/**
 * Compute comprehensive resilience score report for a given selector.
 */
export function scoreSelectorResilience(
  selector: string,
  probeResult?: SelectorValidationResult,
  precedingSteps?: PrecedingStepContext[]
): SelectorScoreReport {
  const tier = detectResilienceTier(selector);
  const status = classifyPresenceStatus(probeResult, precedingSteps);
  const warnings: string[] = [];

  let score = TIER_SCORES[tier];

  // Penalties
  if (isAutoGeneratedSelector(selector)) {
    score -= 25;
    warnings.push('Appears to use autogenerated/hashed identifiers');
  }

  if (selector.length > 60 || selector.split('>').length > 4) {
    score -= 15;
    warnings.push('Brittle path length or excessive combinator depth');
  }

  if (status === 'AmbiguousMultiple') {
    score -= 30;
    warnings.push('Matches multiple elements on page');
  } else if (status === 'NotPresent') {
    score -= 50;
    warnings.push('Element not found in DOM');
  } else if (status === 'DeferredDynamic') {
    score -= 10;
    warnings.push('Element depends on preceding interactive steps');
  }

  if (probeResult && probeResult.matchCount > 0 && probeResult.visibleCount === 0) {
    score -= 40;
    warnings.push('Target element is hidden or invisible in viewport');
  }

  const boundedScore = Math.max(0, Math.min(100, score));
  const isReliable =
    boundedScore >= 70 &&
    (status === 'UniquePresent' || (status === 'DeferredDynamic' && tier === 'TestId'));

  const suggestions = probeResult ? generateSuggestions(probeResult, tier) : undefined;

  const firstMatch = probeResult?.matches[0];

  return {
    selector,
    score: boundedScore,
    tier,
    status,
    isReliable,
    warnings,
    ...(suggestions && suggestions.length > 0 ? { suggestions } : {}),
    details: {
      matchCount: probeResult?.matchCount ?? 0,
      visibleCount: probeResult?.visibleCount ?? 0,
      isClickable: firstMatch?.isClickable,
      isInShadowRoot: firstMatch?.isInShadowRoot,
      isDynamicDeferred: status === 'DeferredDynamic',
    },
  };
}

/**
 * Rank candidate selectors in descending order of stability and resilience score.
 */
export function rankSelectorsByResilience(
  candidates: string[],
  probeResults?: Map<string, SelectorValidationResult>,
  precedingSteps?: PrecedingStepContext[]
): SelectorScoreReport[] {
  const reports = candidates.map((cand) =>
    scoreSelectorResilience(cand, probeResults?.get(cand), precedingSteps)
  );

  return reports.sort((a, b) => b.score - a.score);
}
